version: 2.1
orbs:
  maven: circleci/maven@0.0.12

defaults: &defaults
  working_directory: /tmp/repo

jobs:
  install:
    <<: *defaults
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
            - repo

  integration-test:
    <<: *defaults
    machine: #run as a virtual machine so we can start docker containers
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: /tmp/
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Install maven
          command: sudo apt-get install maven
      - run:
          name: Generate checksum of the migration script
          environment:
            TEST_CBIOPORTAL_DOCKER_IMAGE: cbioportal/cbioportal:3.1.4
          command: /tmp/repo/src/test/resources/local_database/db_content_fingerprint.sh > /tmp/db_data_md5key
      - restore_cache:
          keys:
            - v3-database-files-{{ checksum "/tmp/db_data_md5key" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run integration tests
          command: mvn clean verify -P integration-test -DskipUnitTests=true
      - run:
          name: Change owner of MySQL database files (needed by cache)
          command: |         
              sudo chmod -R 777 /tmp/mysql_data_integration_test && \
              sudo chown -R circleci:circleci /tmp/mysql_data_integration_test
      - save_cache:
          paths:
          - /tmp/mysql_data_integration_test
          key: v3-database-files-{{ checksum "/tmp/db_data_md5key" }}
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}

workflows:
  version: 2
  maven_unit_test:
    jobs:
    - maven/test
  maven_integration_test:
    jobs:
      - install
      - integration-test:
          requires:
              - install