# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
defaults: &defaults
    working_directory: /tmp/repo
    docker:
        # specify the version you desire here
        - image: circleci/openjdk:8-jdk

version: 2
jobs:
    install:
        <<: *defaults
        steps:
             - checkout
             # this is needed because we are using a virtual machine for the end to end tests below
             - persist_to_workspace:
                 root: /tmp
                 paths:
                     - repo

    end_to_end_tests_localdb:
        working_directory: /tmp/repo
        machine: #run as a virtual machine so we can start docker containers
            enabled: true
            image: ubuntu-1604:201903-01
        environment:
            E2E_CBIOPORTAL_HOST_NAME: cbioportal
            CBIOPORTAL_URL: http://$E2E_CBIOPORTAL_HOST_NAME:8081
            PORTAL_HOME: /tmp/repo
            TEST_HOME: /tmp/repo/src/test/resources/local_database
            DB_HOST: cbioDB
            DB_USER: cbio
            DB_PASSWORD: P@ssword1
            DB_PORTAL_DB_NAME: cbioportal
        steps:
            - attach_workspace:
                at: /tmp/
            - run:
                name: update apt-get
                command: sudo apt-get update
            - run:
                name: install maven
                command: sudo apt-get install maven
            - run:
                name: setup cbioportal docker containers
                command: |
                    cd /tmp/repo/src/test/resources/local_database/ && \
                    ./setup_dockers.sh
            - run: 
                name: 
                command: mvn clean install
        when: always

workflows:
    version: 2
    install_and_test:
        jobs:
            - install
            - end_to_end_tests_localdb:
                requires:
                    - install